In [1]:
import cv2
import numpy as np

In [8]:
file_dir='./input/'

digits = cv2.imread(file_dir+"digits.png", cv2.IMREAD_GRAYSCALE)
test_digits = cv2.imread(file_dir+"test_digits.png", cv2.IMREAD_GRAYSCALE)
print(digits,'\n -------------- \n',test_digits)



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 
 -------------- 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
...

In [ ]:
source:
https://pysource.com/2018/08/26/knn-handwritten-digits-recognition-opencv-3-4-with-python-3-tutorial-36/https://pysource.com/2018/08/26/knn-handwritten-digits-recognition-opencv-3-4-with-python-3-tutorial-36/